PREFIX eos: <https://EOS-STPA.github.io/EOS-STPA/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?saic ?hazard ?controlSubject ?controlObject
       ?conditionObject ?faultMode ?ssc ?sscLabel
WHERE {
  ?saic rdf:type eos:DelayedRedLightSAIC .
  ?saic eos:leadsTo ?hazard .
  ?saic eos:requiresControlSubject ?controlSubject .
  ?saic eos:requiresControlObject ?controlObject .
  ?saic eos:hasConditionObject ?conditionObject .
  ?saic eos:hasFaultMode ?faultMode .
  ?saic eos:isOperationalizedBy ?ssc .
  ?ssc rdfs:label ?sscLabel .
}
